services:
  - type: web
    name: artificial-health-center
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    pythonVersion: 3.11.9
    autoDeploy: true
